services:
  - type: web
    name: resumeai-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    nodeVersion: 18.20.8
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 